%% This example illustrates how the Toolkit could be used to develop a hydrant rating curve used in fire flow studies. 
% This curve shows the amount of flow available at a node in the system as a function of pressure. 
% The curve is generated by running a number of steady state hydraulic analyses with the node of interest subjected 
% to a different demand in each analysis. For this example we assume that the ID label of the node of interest is MyNode 
% and that N different demand levels stored in the array D need to be examined. The corresponding pressures will be stored in P.
% To keep the code more readable, no error checking is made on the results returned from the Toolkit function calls.

%% https://github.com/OpenWaterAnalytics/EPANET/wiki/Example-2

%Clear 
clear; close('all'); clc;
start_toolkit;

% Load a network
d = epanet('Net1.inp');

% Select node of interest
nodeID = '32';

% Select number of iterations
r = 1:0.5:10;

d.openHydraulicAnalysis;

nodeIndex = d.getNodeIndex(nodeID);

B = d.getNodeBaseDemands{1}(nodeIndex); % {1} beacause its category
D = B.*r;

N = length(D);

%%
for i = 1:N
    d.setNodeBaseDemands(nodeIndex, D(i));
    d.initializeHydraulicAnalysis;
    d.runHydraulicAnalysis;
    P(i) = d.getNodePressure(nodeIndex);
end

d.closeHydraulicAnalysis;

% Unload library
d.unload

% Plots
plot(D,P,'-x')  
xlabel(['Base Demand (', d.NodeDemandUnits, ')'])
ylabel(['Pressure (', d.NodePressureUnits,')'])

